### ISSUE TITLE
Error: Assertion Failed: When watching the 'args' on a GlimmerComponent, you must watch a value on the args. You cannot watch the object itself, as it never changes.

### ISSUE THREAD

**Issue by poplevente** [sinankeskin/ember-swiper#76]
Hi All,

i'm getting the following error:

Error: Assertion Failed: When watching the 'args' on a GlimmerComponent, you must watch a value on the args. You cannot watch the object itself, as it never changes.

i'm using:
Ember            : 3.13.3
Ember Data       : 3.13.2

"ember-swiper5": "1.2.8",
"@glimmer/component": "1.0.0"

i used the simple example from the readme. does anyone know what could be?

**Comment by poplevente** [comment]
seems that i had an older ember-cli-babel. is it possible to use the swiper on ember version 3.12? we have that and we don't want to make upgrade atm

**Comment by sinankeskin** [comment]
Any news on this? Minimum emberjs version is 3.16 now but I'd like to help.
